#!/usr/bin/env Rscript
#
# QIIME2 16S Amplicon Analysis — Comprehensive Visualization & Data Processing Script
# ================================================================================
# This script works with standard QIIME2 pipeline output files,
# generates publication-quality visualizations, and prepares input files
# for downstream functional prediction (FAPROTAX and PICRUSt2).
#
# Usage:
#   1. Place this script in the QIIME2 project root directory (same directory as
#      metadata.txt; results/export/ should be generated by the pipeline)
#   2. Run directly: Rscript QIIME2_16S_visualization_EN.R [options]
#      All parameters have defaults; override via command line (--help/-h for details)
#   3. The script automatically reads data from results/export/ and outputs
#      to subdirectories within results/export/
#
# Post-run directory structure (under project root):
#   results/export/
#   ├── alpha/           -- Alpha diversity boxplots
#   ├── beta/            -- Beta diversity PCoA plots
#   ├── taxa/            -- Phylum-level composition plots
#   ├── heatmap/         -- Genus-level heatmap
#   ├── faprotax/        -- FAPROTAX input files
#   ├── picrust2/        -- PICRUSt2 input files
#   └── feature_tables/  -- Processed taxonomy and abundance tables
# ================================================================================

# ============================================================
# 0. Configuration — all parameters have defaults,
#    override via command line
# ============================================================

# ---- CLI argument parsing ----
parse_cli_args <- function() {
  args <- commandArgs(trailingOnly = TRUE)
  params <- list()

  short_map <- c(
    m = "metadata",
    e = "export_dir",
    g = "group_col",
    n = "top_n_genera",
    y = "top_n_phyla_stacked",
    c = "color_palette",
    a = "p_adjust_method"
  )

  i <- 1
  while (i <= length(args)) {
    if (args[i] %in% c("--help", "-h")) {
      cat("QIIME2 16S Amplicon Visualization Script\n")
      cat("Usage: Rscript QIIME2_16S_visualization_EN.R [options]\n")
      cat("All parameters have defaults; only specify those you need to override.\n\n")
      cat("Path parameters:\n")
      cat("  -m, --metadata=<file>        Metadata file path (default: metadata.txt)\n")
      cat("  -e, --export-dir=<dir>       Export base directory (default: results/export)\n")
      cat("                                Changes adjust all input/output paths automatically\n\n")
      cat("Data parameters:\n")
      cat("  -g, --group-col=<col>        Group column name (default: Group)\n\n")
      cat("Visualization parameters:\n")
      cat("  -n, --top-n-genera=<n>       Top N genera for heatmap (default: 30)\n")
      cat("  -y, --top-n-phyla-stacked=<n> Top N phyla for stacked barplot (default: 8)\n")
      cat("  -c, --color-palette=<name>   Color palette: npg/aaas/nejm/lancet/jco/jama/uchicago (default: npg)\n")
      cat("  -a, --p-adjust-method=<name> Pairwise test correction: none/BH (default: none)\n")
      quit(save = "no", status = 0)
    } else if (grepl("^--", args[i])) {
      kv <- sub("^--", "", args[i])
      if (grepl("=", kv, fixed = TRUE)) {
        parts <- strsplit(kv, "=", fixed = TRUE)[[1]]
        name <- gsub("-", "_", parts[1])
        params[[name]] <- parts[2]
      }
    } else if (grepl("^-", args[i])) {
      short <- sub("^-", "", args[i])
      flag <- substr(short, 1, 1)
      if (flag != "h") {
        if (grepl("=", short, fixed = TRUE)) {
          val <- sub("^[^=]+=", "", short)
          full <- short_map[flag]
          if (!is.na(full)) params[[full]] <- val
        } else if (nchar(short) == 1) {
          full <- short_map[flag]
          if (!is.na(full) && i < length(args)) {
            i <- i + 1
            params[[full]] <- args[i]
          }
        }
      }
    }
    i <- i + 1
  }
  return(params)
}

cli <- parse_cli_args()

# Helper: use CLI value if provided, otherwise default
use_param <- function(cli_val, default) {
  if (is.null(cli_val)) default else cli_val
}

# ---- Path parameters ----
setwd(".")
export_dir        <- use_param(cli[["export_dir"]], "results/export")
metadata_file     <- use_param(cli[["metadata"]], "metadata.txt")

# ---- Data parameters ----
group_col         <- use_param(cli[["group_col"]], "Group")

# ---- Input file paths (auto-built from export_dir) ----
alpha_diversity_file  <- file.path(export_dir, "evenness_vector.tsv")
feature_table_file    <- file.path(export_dir, "feature-table.tsv")
rarefied_table_file   <- file.path(export_dir, "rarefied_table.tsv")
taxonomy_file         <- file.path(export_dir, "taxonomy.tsv")
dna_sequences_file    <- file.path(export_dir, "dna-sequences.fasta")
rarefied_biom_file    <- file.path(export_dir, "rarefied_table.biom")

# ---- Output subdirectories (auto-built from export_dir) ----
output_dirs <- file.path(export_dir,
  c("alpha", "beta", "taxa", "heatmap", "faprotax",
    "picrust2", "feature_tables"))

# ---- Visualization parameters ----
top_n_genera       <- as.numeric(use_param(cli[["top_n_genera"]], 30))
top_n_phyla_stacked <- as.numeric(use_param(cli[["top_n_phyla_stacked"]], 8))

# ---- Color palette ----
color_palette      <- use_param(cli[["color_palette"]], "npg")

# ---- Statistics ----
p_adjust_method    <- use_param(cli[["p_adjust_method"]], "none")

# ============================================================
# 1. Load required R packages
# ============================================================

cat("========================================\n")
cat("QIIME2 16S Visualization Pipeline\n")
cat("========================================\n\n")

required_packages <- c(
  "ggplot2", "tidyr", "dplyr", "tibble", "readr",
  "vegan", "ape", "pheatmap", "RColorBrewer", "grDevices",
  "patchwork", "ggsignif", "ggsci"
)

check_packages <- function(pkgs) {
  missing <- c()
  for (pkg in pkgs) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      missing <- c(missing, pkg)
    }
  }
  if (length(missing) > 0) {
    cat("Installing missing packages:", paste(missing, collapse = ", "), "\n")
    install.packages(missing, repos = "https://cloud.r-project.org", quiet = TRUE)
  }
  invisible(lapply(pkgs, library, character.only = TRUE, quietly = TRUE))
}

cat("[1/8] Loading R packages...\n")
check_packages(required_packages)
cat("       All packages loaded successfully.\n\n")

# Color helper: get colors from ggsci journal palettes based on group count
get_group_colors <- function(n, palette_name = color_palette) {
  base <- switch(palette_name,
    npg    = pal_npg()(10),
    aaas   = pal_aaas()(10),
    nejm   = pal_nejm()(8),
    lancet = pal_lancet()(9),
    jco    = pal_jco()(10),
    jama   = pal_jama()(7),
    uchicago = pal_uchicago()(9),
    pal_npg()(10)
  )
  if (n <= length(base)) base[1:n] else grDevices::colorRampPalette(base)(n)
}

# ============================================================
# 2. Create output directories
# ============================================================

cat("[2/8] Creating output directories...\n")
for (dir_name in output_dirs) {
  if (!dir.exists(dir_name)) {
    dir.create(dir_name, recursive = TRUE)
    cat("       Created:", dir_name, "\n")
  }
}
cat("       Output directories ready.\n\n")

# ============================================================
# 3. Read metadata
# ============================================================

cat("[3/8] Reading input data...\n")

if (!file.exists(metadata_file)) {
  stop("Metadata file not found: ", metadata_file,
    "\nPlease check the metadata_file path in the configuration section.")
}

metadata <- read.table(
  metadata_file,
  sep = "\t",
  header = TRUE,
  row.names = 1,
  check.names = FALSE,
  comment.char = "",
  strip.white = TRUE,
  stringsAsFactors = FALSE
)

# Clean column names (remove leading # if present)
colnames(metadata) <- gsub("^#", "", colnames(metadata))

# Check group column exists
if (!group_col %in% colnames(metadata)) {
  stop("Group column '", group_col, "' not found in metadata.\n",
    "Available columns: ", paste(colnames(metadata), collapse = ", "))
}

# Convert group column to factor
metadata[[group_col]] <- as.factor(metadata[[group_col]])
cat("       Metadata loaded:", nrow(metadata), "samples,",
  ncol(metadata), "columns\n")
cat("       Groups:", paste(levels(metadata[[group_col]]), collapse = " / "), "\n")

# ============================================================
# 4. Read feature table
# ============================================================

if (!file.exists(feature_table_file)) {
  stop("Feature table not found: ", feature_table_file)
}

# Skip the first comment line (# Constructed from biom file)
feature_table <- read.table(
  feature_table_file,
  sep = "\t",
  skip = 1,
  header = TRUE,
  check.names = FALSE,
  row.names = 1,
  comment.char = ""
)

# Ensure data is numeric matrix
feature_table <- as.matrix(feature_table)
mode(feature_table) <- "numeric"

# Keep only samples present in metadata
common_samples <- intersect(colnames(feature_table), rownames(metadata))
feature_table <- feature_table[, common_samples, drop = FALSE]
metadata <- metadata[common_samples, , drop = FALSE]

cat("       Feature table loaded:", nrow(feature_table), "ASVs,",
  ncol(feature_table), "samples\n")
cat("       Total reads:", sum(feature_table), "\n")

# ============================================================
# 5. Read and process taxonomy
# ============================================================

if (!file.exists(taxonomy_file)) {
  stop("Taxonomy file not found: ", taxonomy_file)
}

taxonomy_raw <- read.table(
  taxonomy_file,
  sep = "\t",
  header = TRUE,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

# Parse taxonomy string into individual levels
parse_taxonomy <- function(taxon_string) {
  result <- c("Unassigned", "Unassigned", "Unassigned",
              "Unassigned", "Unassigned", "Unassigned", "Unassigned")
  names(result) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")

  parts <- strsplit(trimws(taxon_string), ";")[[1]]
  for (part in parts) {
    if (nchar(part) < 3) next
    prefix <- substr(part, 1, 1)
    value <- substr(part, 4, nchar(part))
    if (value == "") value <- "Unassigned"

    level_name <- switch(prefix,
      "d" = "Kingdom",
      "p" = "Phylum",
      "c" = "Class",
      "o" = "Order",
      "f" = "Family",
      "g" = "Genus",
      "s" = "Species",
      NA
    )
    if (!is.na(level_name)) {
      result[level_name] <- value
    }
  }
  return(result)
}

# Parse all taxonomy strings
tax_parsed <- t(sapply(taxonomy_raw$Taxon, parse_taxonomy, USE.NAMES = FALSE))
taxonomy <- as.data.frame(tax_parsed, stringsAsFactors = FALSE)
taxonomy$FeatureID <- taxonomy_raw[["Feature ID"]]
taxonomy$Confidence <- taxonomy_raw$Confidence

# Build full taxonomy path (for FAPROTAX)
taxonomy$FullPath <- apply(tax_parsed, 1, function(x) {
  paste(x, collapse = ";")
})

# Build compact path: trim trailing Unassigned
build_compact_path <- function(levels_vec) {
  non_na_idx <- which(levels_vec != "Unassigned")
  if (length(non_na_idx) == 0) return("Unassigned")
  last_idx <- max(non_na_idx)
  paste(levels_vec[1:last_idx], collapse = ";")
}
taxonomy$CompactPath <- apply(tax_parsed, 1, build_compact_path)

# Create Feature ID to taxonomy mapping
tax_map <- setNames(taxonomy$FullPath, taxonomy$FeatureID)

cat("       Taxonomy entries:", nrow(taxonomy), "\n")
cat("       Phyla annotated:", length(unique(taxonomy$Phylum[taxonomy$Phylum != "Unassigned"])), "\n")

# ============================================================
# 6. Save processed data tables
# ============================================================

cat("\n[4/8] Saving processed data tables...\n")

# 6a. Processed taxonomy table (all levels split, Unassigned filled)
taxonomy_out <- taxonomy[, c("FeatureID", "Kingdom", "Phylum", "Class",
                              "Order", "Family", "Genus", "Species",
                              "FullPath", "Confidence")]
colnames(taxonomy_out)[1] <- "Feature_ID"
write.table(
  taxonomy_out,
  file = "results/export/feature_tables/taxonomy_processed.tsv",
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)
cat("       [OK] results/export/feature_tables/taxonomy_processed.tsv\n")

# 6b. Feature table with taxonomy annotation
merged_data <- as.data.frame(feature_table)
merged_data$FeatureID <- rownames(merged_data)
merged_data <- merge(merged_data, taxonomy[, c("FeatureID", "FullPath", "CompactPath")],
                     by = "FeatureID", all.x = TRUE)

# Reorder columns
merged_data <- merged_data[, c("FeatureID", "FullPath", "CompactPath",
                                setdiff(colnames(merged_data),
                                        c("FeatureID", "FullPath", "CompactPath")))]

write.table(
  merged_data,
  file = "results/export/feature_tables/feature_table_with_taxonomy.tsv",
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)
cat("       [OK] results/export/feature_tables/feature_table_with_taxonomy.tsv\n")

# ============================================================
# 7. Alpha diversity analysis
# ============================================================

cat("\n[5/8] Generating visualizations...\n")
cat("       Processing alpha diversity...\n")

# 7a. Calculate alpha diversity metrics
# ------------------------------------------------------------------
# Use the rarefied feature table for alpha diversity calculations,
# consistent with QIIME2 core-metrics-phylogenetic, eliminating
# sequencing depth effects on richness estimates.
if (!file.exists(rarefied_table_file)) {
  stop("Rarefied table not found: ", rarefied_table_file,
       "\nPlease run qiime diversity core-metrics-phylogenetic",
       " and export rarefied_table.tsv")
}

rarefied_table <- read.table(
  rarefied_table_file,
  sep = "\t",
  skip = 1,
  header = TRUE,
  check.names = FALSE,
  row.names = 1,
  comment.char = ""
)
rarefied_table <- as.matrix(rarefied_table)
mode(rarefied_table) <- "numeric"

# Keep only samples present in metadata
common_rare <- intersect(colnames(rarefied_table), rownames(metadata))
rarefied_table <- rarefied_table[, common_rare, drop = FALSE]

ft_t <- t(rarefied_table)  # Transpose: vegan requires samples as rows, ASVs as columns

observed_features <- specnumber(ft_t)
shannon_div <- diversity(ft_t, index = "shannon")
simpson_div <- diversity(ft_t, index = "simpson")
est_rich <- estimateR(ft_t)
chao1_div <- est_rich["S.chao1", ]
ace_div   <- est_rich["S.ACE", ]

# Pielou evenness (calculated directly from rarefied table: J = H / ln(S), no QIIME2 export needed)
pielou_div <- shannon_div / log(observed_features)
pielou_div[observed_features <= 1] <- 0

# Combine all metrics into a data frame
alpha_metrics_df <- data.frame(
  SampleID = names(observed_features),
  observed_features = observed_features,
  shannon = shannon_div,
  simpson = simpson_div,
  chao1 = chao1_div,
  ACE = ace_div,
  pielou_evenness = pielou_div[names(observed_features)],
  row.names = NULL, stringsAsFactors = FALSE
)

# Merge with metadata
alpha_plot_data <- merge(
  alpha_metrics_df,
  metadata[, group_col, drop = FALSE],
  by.x = "SampleID", by.y = "row.names"
)

# Save all alpha diversity metrics to file
write.table(alpha_plot_data,
  file = "results/export/feature_tables/alpha_diversity_metrics.tsv",
  sep = "\t", row.names = FALSE, quote = FALSE)
cat("       [OK] results/export/feature_tables/alpha_diversity_metrics.tsv\n")

# Metrics to plot (including Pielou evenness)
plot_metrics <- c("observed_features", "shannon", "simpson", "chao1", "pielou_evenness")
metric_labels <- c(
  observed_features = "Observed ASVs",
  shannon = "Shannon",
  simpson = "Simpson",
  chao1 = "Chao1",
  pielou_evenness = "Pielou evenness"
)

# Reshape to long format, filter non-finite values
alpha_long <- pivot_longer(
  alpha_plot_data,
  cols = all_of(plot_metrics),
  names_to = "Metric", values_to = "Value"
)
alpha_long[[group_col]] <- as.factor(alpha_long[[group_col]])
alpha_long <- alpha_long[is.finite(alpha_long$Value), ]

# Log filtered samples
for (m in plot_metrics) {
  n_inf <- sum(!is.finite(alpha_plot_data[[m]]))
  if (n_inf > 0) {
    cat("       [Note]", m, "contains", n_inf, "non-finite values\n")
  }
}

# 7b. Alpha diversity statistical tests
# ------------------------------------------------------------------
cat("       Alpha diversity statistics:\n")

for (metric in plot_metrics) {
  df_sub <- alpha_plot_data[is.finite(alpha_plot_data[[metric]]), ]

  # Kruskal-Wallis
  kw <- kruskal.test(as.formula(paste(metric, "~", group_col)), data = df_sub)
  cat("         ", metric, ": Kruskal-Wallis p =",
      format.pval(kw$p.value, digits = 4), "\n")

  # Pairwise Wilcoxon + BH correction
  pw <- suppressWarnings(
    pairwise.wilcox.test(df_sub[[metric]], df_sub[[group_col]],
                         p.adjust.method = p_adjust_method))
  p_mat <- pw$p.value
  if (!is.null(p_mat)) {
    g_levels <- levels(df_sub[[group_col]])
    for (i in seq_len(length(g_levels) - 1)) {
      for (j in (i + 1):length(g_levels)) {
        pv <- tryCatch(
          if (g_levels[j] %in% rownames(p_mat) && g_levels[i] %in% colnames(p_mat))
            p_mat[g_levels[j], g_levels[i]]
          else if (g_levels[i] %in% rownames(p_mat) && g_levels[j] %in% colnames(p_mat))
            p_mat[g_levels[i], g_levels[j]]
          else NA_real_,
          error = function(e) NA_real_)
        if (!is.na(pv)) {
          star <- if (pv < 0.001) "***" else if (pv < 0.01) "**" else if (pv < 0.05) "*" else "ns"
          cat("             ", g_levels[i], "vs", g_levels[j],
              ": p =", format.pval(pv, digits = 4), star, "\n")
        }
      }
    }
  }
}

# 7b2. Output alpha diversity statistics summary table (mean ± SD + Kruskal-Wallis + pairwise Wilcoxon p-values)
# ------------------------------------------------------------------
cat("       Saving alpha diversity statistics table...\n")

stats_list <- list()
for (metric in plot_metrics) {
  df_sub <- alpha_plot_data[is.finite(alpha_plot_data[[metric]]), ]

  # Per-group mean ± SD
  group_stats <- df_sub %>%
    group_by(!!sym(group_col)) %>%
    summarise(Mean = mean(.data[[metric]]), SD = sd(.data[[metric]]), .groups = "drop")

  # Kruskal-Wallis
  kw <- kruskal.test(as.formula(paste(metric, "~", group_col)), data = df_sub)
  kw_p <- kw$p.value
  kw_star <- if (kw_p < 0.001) "***" else if (kw_p < 0.01) "**" else if (kw_p < 0.05) "*" else "ns"

  # Pairwise Wilcoxon
  pw <- suppressWarnings(
    pairwise.wilcox.test(df_sub[[metric]], df_sub[[group_col]],
                         p.adjust.method = p_adjust_method))
  p_mat <- pw$p.value
  pairwise_list <- c()
  if (!is.null(p_mat)) {
    g_levels <- levels(df_sub[[group_col]])
    for (i in seq_len(length(g_levels) - 1)) {
      for (j in (i + 1):length(g_levels)) {
        pv <- tryCatch(
          if (g_levels[j] %in% rownames(p_mat) && g_levels[i] %in% colnames(p_mat))
            p_mat[g_levels[j], g_levels[i]]
          else if (g_levels[i] %in% rownames(p_mat) && g_levels[j] %in% colnames(p_mat))
            p_mat[g_levels[i], g_levels[j]]
          else NA_real_,
          error = function(e) NA_real_)
        if (!is.na(pv)) {
          star <- if (pv < 0.001) "***" else if (pv < 0.01) "**" else if (pv < 0.05) "*" else "ns"
          pairwise_list <- c(pairwise_list, sprintf("%s_vs_%s=%.4g%s", g_levels[i], g_levels[j], pv, star))
        }
      }
    }
  }
  pairwise_str <- paste(pairwise_list, collapse = "; ")

  # Assemble row for this metric
  row_df <- data.frame(Metric = metric, Kruskal_Wallis_p = kw_p,
    Kruskal_Wallis_sig = kw_star, stringsAsFactors = FALSE)
  for (g in levels(df_sub[[group_col]])) {
    gd <- group_stats[group_stats[[group_col]] == g, ]
    row_df[[paste0(g, "_mean")]] <- round(gd$Mean, 4)
    row_df[[paste0(g, "_SD")]]   <- round(gd$SD, 4)
  }
  row_df$Pairwise_Wilcoxon <- pairwise_str
  stats_list[[metric]] <- row_df
}
stats_summary <- do.call(rbind, stats_list)
write.table(stats_summary,
  file = "results/export/feature_tables/alpha_diversity_statistics.tsv",
  sep = "\t", row.names = FALSE, quote = FALSE)
cat("       [OK] results/export/feature_tables/alpha_diversity_statistics.tsv\n")

# 7c. Alpha diversity boxplots with significance stars (including Kruskal-Wallis p-value)
# ------------------------------------------------------------------
plot_list <- list()

for (metric in plot_metrics) {
  df_sub <- alpha_long[alpha_long$Metric == metric, ]
  g_levels <- levels(df_sub[[group_col]])

  # Kruskal-Wallis test (p-value displayed on plot)
  kw_test <- kruskal.test(as.formula(paste("Value", "~", group_col)), data = df_sub)
  kw_label <- sprintf("Kruskal-Wallis p = %s", format.pval(kw_test$p.value, digits = 3))

  # Pairwise Wilcoxon test
  pw <- suppressWarnings(
    pairwise.wilcox.test(df_sub$Value, df_sub[[group_col]],
                         p.adjust.method = p_adjust_method))
  p_mat <- pw$p.value

  # Build ggsignif parameters
  comp_list <- list()
  annot_vec <- c()
  for (i in seq_len(length(g_levels) - 1)) {
    for (j in (i + 1):length(g_levels)) {
      pv <- tryCatch(
        if (g_levels[j] %in% rownames(p_mat) && g_levels[i] %in% colnames(p_mat))
          p_mat[g_levels[j], g_levels[i]]
        else if (g_levels[i] %in% rownames(p_mat) && g_levels[j] %in% colnames(p_mat))
          p_mat[g_levels[i], g_levels[j]]
        else NA_real_,
        error = function(e) NA_real_)
      if (!is.na(pv) && pv < 0.05) {
        comp_list <- c(comp_list, list(c(g_levels[i], g_levels[j])))
        star <- if (pv < 0.001) "***" else if (pv < 0.01) "**" else "*"
        annot_vec <- c(annot_vec, star)
      }
    }
  }

  p <- ggplot(df_sub, aes(x = !!sym(group_col), y = Value, fill = !!sym(group_col))) +
    geom_boxplot(outlier.shape = NA, alpha = 0.6, width = 0.6) +
    geom_jitter(aes(color = !!sym(group_col)), width = 0.15, size = 1.5, alpha = 0.8) +
    scale_fill_manual(values = get_group_colors(nlevels(df_sub[[group_col]]))) +
    scale_color_manual(values = get_group_colors(nlevels(df_sub[[group_col]]))) +
    labs(title = metric_labels[metric], subtitle = kw_label, x = NULL, y = "Value") +
    theme_bw(base_size = 12) +
    theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 12),
          plot.subtitle = element_text(hjust = 0.5, size = 9, color = "grey40"),
          legend.position = "none",
          axis.text.x = element_text(angle = 45, hjust = 1),
          panel.grid.minor = element_blank())

  if (length(comp_list) > 0) {
    p <- p + geom_signif(comparisons = comp_list, annotation = annot_vec,
                         step_increase = 0.1, tip_length = 0.02, textsize = 3.5)
  }
  plot_list[[metric]] <- p
}

# 3x2 grid (5 metrics)
p_alpha_combined <- wrap_plots(plotlist = plot_list, ncol = 2, nrow = 3)
ggsave(filename = "results/export/alpha/alpha_diversity_boxplot.pdf",
       plot = p_alpha_combined, width = 10, height = 11, device = cairo_pdf)
cat("       [OK] results/export/alpha/alpha_diversity_boxplot.pdf\n")

# Save individual boxplots for each metric
for (metric in plot_metrics) {
  ggsave(filename = paste0("results/export/alpha/alpha_boxplot_", metric, ".pdf"),
         plot = plot_list[[metric]], width = 5, height = 4, device = cairo_pdf)
}
cat("       [OK] results/export/alpha/alpha_boxplot_*.pdf (5 individual plots)\n")

# 7d. Rarefaction curves (group-averaged)
# ------------------------------------------------------------------
cat("       Generating rarefaction curves...\n")

# Manual rarefaction: use apply + rarefy to avoid lapply/do.call compatibility issues
rarefy_step <- 100
min_depth <- min(rowSums(ft_t))
rarefy_depths <- seq(from = rarefy_step, to = min_depth, by = rarefy_step)

rare_mat <- suppressWarnings(apply(ft_t, 1, function(row) {
  rarefy(row, rarefy_depths)
}))
# rare_mat: rows = sequencing depths, columns = samples
rare_df <- data.frame(
  SampleID = rep(colnames(rare_mat), each = nrow(rare_mat)),
  Reads    = rep(rarefy_depths, ncol(rare_mat)),
  ASVs     = as.vector(rare_mat),
  stringsAsFactors = FALSE
)
# Match group info by SampleID
rare_df[[group_col]] <- metadata[as.character(rare_df$SampleID), group_col, drop = TRUE]

# Calculate mean and SE per Reads depth per group (base R aggregate)
rare_agg <- aggregate(
  x = rare_df$ASVs,
  by = list(Group = rare_df[[group_col]], Reads = rare_df$Reads),
  FUN = function(x) c(mean = mean(x, na.rm = TRUE), se = sd(x, na.rm = TRUE) / sqrt(length(x)))
)
rare_summary <- do.call(data.frame, rare_agg)
colnames(rare_summary) <- c(group_col, "Reads", "mean_ASVs", "se_ASVs")

p_rarefaction <- ggplot(rare_summary, aes(x = Reads, y = mean_ASVs,
                                           color = !!sym(group_col),
                                           fill = !!sym(group_col))) +
  geom_ribbon(aes(ymin = mean_ASVs - se_ASVs, ymax = mean_ASVs + se_ASVs),
              alpha = 0.2, color = NA) +
  geom_line(linewidth = 1) +
  scale_color_manual(values = get_group_colors(nlevels(rare_summary[[group_col]]))) +
  scale_fill_manual(values = get_group_colors(nlevels(rare_summary[[group_col]]))) +
  labs(title = "Rarefaction Curves",
       x = "Number of Reads", y = "Number of ASVs",
       color = group_col, fill = group_col) +
  theme_bw(base_size = 14) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.position = "right", panel.grid.minor = element_blank())

ggsave(filename = "results/export/alpha/rarefaction_curves.pdf",
       plot = p_rarefaction, width = 8, height = 6, device = cairo_pdf)
cat("       [OK] results/export/alpha/rarefaction_curves.pdf\n")

# ============================================================
# 8. Beta diversity — PCoA and PERMANOVA
# ============================================================

cat("       Processing beta diversity...\n")

# Filter ASVs with zero abundance across all samples
ft_sub <- feature_table[rowSums(feature_table) > 0, ]

# ---------- 8a. Bray-Curtis PCoA ----------
cat("       Bray-Curtis PCoA...\n")
bc_dist <- vegdist(t(ft_sub), method = "bray")

pcoa_result <- cmdscale(bc_dist, k = min(10, ncol(ft_sub) - 1), eig = TRUE)
var_exp <- round(pcoa_result$eig[1:4] / sum(pcoa_result$eig[pcoa_result$eig > 0]) * 100, 1)

pcoa_df <- as.data.frame(pcoa_result$points)
colnames(pcoa_df) <- paste0("PCo", seq_len(ncol(pcoa_df)))
pcoa_df$SampleID <- rownames(pcoa_df)
pcoa_df <- merge(pcoa_df, metadata[, group_col, drop = FALSE],
                 by.x = "SampleID", by.y = "row.names")

# PERMANOVA
adonis_formula <- as.formula(paste("bc_dist ~", group_col))
adonis_result <- adonis2(adonis_formula, data = metadata, permutations = 999)
print(adonis_result)
r2 <- round(adonis_result[1, "R2"], 3)
p_col <- grep("Pr", colnames(adonis_result))[1]
pval <- adonis_result[1, p_col]
pval_str <- ifelse(pval < 0.001, format.pval(pval, digits = 4),
                   paste0("= ", format.pval(pval, digits = 4)))

# PCoA plot
p_pcoa <- ggplot(pcoa_df, aes(x = PCo1, y = PCo2, color = !!sym(group_col))) +
  geom_point(size = 3, alpha = 0.8)

min_group_size <- min(table(pcoa_df[[group_col]]))
if (min_group_size >= 4) {
  p_pcoa <- p_pcoa +
    stat_ellipse(aes(fill = !!sym(group_col)),
      geom = "polygon", alpha = 0.1, level = 0.95, show.legend = FALSE)
}

p_pcoa <- p_pcoa +
  scale_color_manual(values = get_group_colors(nlevels(pcoa_df[[group_col]]))) +
  scale_fill_manual(values = get_group_colors(nlevels(pcoa_df[[group_col]]))) +
  labs(title = "Beta Diversity - Bray-Curtis PCoA",
       x = paste0("PCo1 (", var_exp[1], "%)"),
       y = paste0("PCo2 (", var_exp[2], "%)"),
       color = group_col,
       caption = paste0("PERMANOVA: R² = ", r2, ", p ", pval_str)) +
  theme_bw(base_size = 14) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.position = "right", panel.grid.minor = element_blank(),
        plot.caption = element_text(hjust = 0.5, size = 10))

ggsave(filename = "results/export/beta/beta_diversity_pcoa_bray_curtis.pdf",
       plot = p_pcoa, width = 8, height = 6, device = cairo_pdf)
cat("       [OK] results/export/beta/beta_diversity_pcoa_bray_curtis.pdf\n")

# Save Bray-Curtis PCoA coordinates
write.table(pcoa_df,
  file = "results/export/beta/bray_curtis_pcoa_coords.tsv",
  sep = "\t", row.names = FALSE, quote = FALSE)
cat("       [OK] results/export/beta/bray_curtis_pcoa_coords.tsv\n")

# Save variance explained
var_exp_df <- data.frame(
  Axis = paste0("PCo", seq_along(var_exp)),
  Variance_percent = var_exp,
  Cumulative_percent = cumsum(var_exp)
)
write.table(var_exp_df,
  file = "results/export/beta/bray_curtis_pcoa_variance.tsv",
  sep = "\t", row.names = FALSE, quote = FALSE)
cat("       [OK] results/export/beta/bray_curtis_pcoa_variance.tsv\n")

# Save full PERMANOVA results
adonis_out <- as.data.frame(adonis_result)
adonis_out$Term <- rownames(adonis_result)
adonis_out <- adonis_out[, c("Term", setdiff(colnames(adonis_out), "Term"))]
write.table(adonis_out,
  file = "results/export/beta/bray_curtis_permanova.tsv",
  sep = "\t", row.names = FALSE, quote = FALSE)
cat("       [OK] results/export/beta/bray_curtis_permanova.tsv\n")

# ---------- 8b. Jaccard PCoA ----------
cat("       Jaccard PCoA...\n")
jacc_dist <- vegdist(t(ft_sub), method = "jaccard", binary = TRUE)

pcoa_jacc <- cmdscale(jacc_dist, k = min(10, ncol(ft_sub) - 1), eig = TRUE)
var_exp_jacc <- round(pcoa_jacc$eig[1:4] / sum(pcoa_jacc$eig[pcoa_jacc$eig > 0]) * 100, 1)

pcoa_jacc_df <- as.data.frame(pcoa_jacc$points)
colnames(pcoa_jacc_df) <- paste0("PCo", seq_len(ncol(pcoa_jacc_df)))
pcoa_jacc_df$SampleID <- rownames(pcoa_jacc_df)
pcoa_jacc_df <- merge(pcoa_jacc_df, metadata[, group_col, drop = FALSE],
                      by.x = "SampleID", by.y = "row.names")

# PERMANOVA
adonis_jacc <- adonis2(as.formula(paste("jacc_dist ~", group_col)),
                       data = metadata, permutations = 999)
print(adonis_jacc)
r2_jacc <- round(adonis_jacc[1, "R2"], 3)
p_col_jacc <- grep("Pr", colnames(adonis_jacc))[1]
pval_jacc <- adonis_jacc[1, p_col_jacc]
pval_jacc_str <- ifelse(pval_jacc < 0.001, format.pval(pval_jacc, digits = 4),
                        paste0("= ", format.pval(pval_jacc, digits = 4)))

# Jaccard PCoA plot
p_jacc <- ggplot(pcoa_jacc_df, aes(x = PCo1, y = PCo2, color = !!sym(group_col))) +
  geom_point(size = 3, alpha = 0.8)

if (min_group_size >= 4) {
  p_jacc <- p_jacc +
    stat_ellipse(aes(fill = !!sym(group_col)),
      geom = "polygon", alpha = 0.1, level = 0.95, show.legend = FALSE)
}

p_jacc <- p_jacc +
  scale_color_manual(values = get_group_colors(nlevels(pcoa_jacc_df[[group_col]]))) +
  scale_fill_manual(values = get_group_colors(nlevels(pcoa_jacc_df[[group_col]]))) +
  labs(title = "Beta Diversity - Jaccard PCoA",
       x = paste0("PCo1 (", var_exp_jacc[1], "%)"),
       y = paste0("PCo2 (", var_exp_jacc[2], "%)"),
       color = group_col,
       caption = paste0("PERMANOVA: R² = ", r2_jacc, ", p ", pval_jacc_str)) +
  theme_bw(base_size = 14) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.position = "right", panel.grid.minor = element_blank(),
        plot.caption = element_text(hjust = 0.5, size = 10))

ggsave(filename = "results/export/beta/beta_diversity_pcoa_jaccard.pdf",
       plot = p_jacc, width = 8, height = 6, device = cairo_pdf)
cat("       [OK] results/export/beta/beta_diversity_pcoa_jaccard.pdf\n")

# Save Jaccard PCoA coordinates
write.table(pcoa_jacc_df,
  file = "results/export/beta/jaccard_pcoa_coords.tsv",
  sep = "\t", row.names = FALSE, quote = FALSE)
cat("       [OK] results/export/beta/jaccard_pcoa_coords.tsv\n")

# Save variance explained
var_exp_jacc_df <- data.frame(
  Axis = paste0("PCo", seq_along(var_exp_jacc)),
  Variance_percent = var_exp_jacc,
  Cumulative_percent = cumsum(var_exp_jacc)
)
write.table(var_exp_jacc_df,
  file = "results/export/beta/jaccard_pcoa_variance.tsv",
  sep = "\t", row.names = FALSE, quote = FALSE)
cat("       [OK] results/export/beta/jaccard_pcoa_variance.tsv\n")

# Save full PERMANOVA results
adonis_jacc_out <- as.data.frame(adonis_jacc)
adonis_jacc_out$Term <- rownames(adonis_jacc)
adonis_jacc_out <- adonis_jacc_out[, c("Term", setdiff(colnames(adonis_jacc_out), "Term"))]
write.table(adonis_jacc_out,
  file = "results/export/beta/jaccard_permanova.tsv",
  sep = "\t", row.names = FALSE, quote = FALSE)
cat("       [OK] results/export/beta/jaccard_permanova.tsv\n")

# ---------- 8c. Weighted UniFrac PCoA ----------
cat("       Weighted UniFrac PCoA...\n")
wuf_dist_file <- "results/export/weighted_unifrac_distance_matrix.tsv"
if (file.exists(wuf_dist_file)) {
  wuf_dist <- as.matrix(read.table(wuf_dist_file, sep = "\t", header = TRUE, row.names = 1, check.names = FALSE))

  pcoa_wuf <- cmdscale(wuf_dist, k = min(10, nrow(wuf_dist) - 1), eig = TRUE)
  var_exp_wuf <- round(pcoa_wuf$eig[1:4] / sum(pcoa_wuf$eig[pcoa_wuf$eig > 0]) * 100, 1)

  pcoa_wuf_df <- as.data.frame(pcoa_wuf$points)
  colnames(pcoa_wuf_df) <- paste0("PCo", seq_len(ncol(pcoa_wuf_df)))
  pcoa_wuf_df$SampleID <- rownames(pcoa_wuf_df)
  pcoa_wuf_df <- merge(pcoa_wuf_df, metadata[, group_col, drop = FALSE],
                        by.x = "SampleID", by.y = "row.names")

  # PERMANOVA
  adonis_wuf <- adonis2(as.formula(paste("wuf_dist ~", group_col)),
                         data = metadata, permutations = 999)
  print(adonis_wuf)
  r2_wuf <- round(adonis_wuf[1, "R2"], 3)
  p_col_wuf <- grep("Pr", colnames(adonis_wuf))[1]
  pval_wuf <- adonis_wuf[1, p_col_wuf]
  pval_wuf_str <- ifelse(pval_wuf < 0.001, format.pval(pval_wuf, digits = 4),
                          paste0("= ", format.pval(pval_wuf, digits = 4)))

  # PCoA plot
  p_wuf <- ggplot(pcoa_wuf_df, aes(x = PCo1, y = PCo2, color = !!sym(group_col))) +
    geom_point(size = 3, alpha = 0.8)

  if (min_group_size >= 4) {
    p_wuf <- p_wuf +
      stat_ellipse(aes(fill = !!sym(group_col)),
        geom = "polygon", alpha = 0.1, level = 0.95, show.legend = FALSE)
  }

  p_wuf <- p_wuf +
    scale_color_manual(values = get_group_colors(nlevels(pcoa_wuf_df[[group_col]]))) +
    scale_fill_manual(values = get_group_colors(nlevels(pcoa_wuf_df[[group_col]]))) +
    labs(title = "Beta Diversity - Weighted UniFrac PCoA",
         x = paste0("PCo1 (", var_exp_wuf[1], "%)"),
         y = paste0("PCo2 (", var_exp_wuf[2], "%)"),
         color = group_col,
         caption = paste0("PERMANOVA: R² = ", r2_wuf, ", p ", pval_wuf_str)) +
    theme_bw(base_size = 14) +
    theme(plot.title = element_text(hjust = 0.5, face = "bold"),
          legend.position = "right", panel.grid.minor = element_blank(),
          plot.caption = element_text(hjust = 0.5, size = 10))

  ggsave(filename = "results/export/beta/beta_diversity_pcoa_weighted_unifrac.pdf",
         plot = p_wuf, width = 8, height = 6, device = cairo_pdf)
  cat("       [OK] results/export/beta/beta_diversity_pcoa_weighted_unifrac.pdf\n")

  # Save PCoA coordinates
  write.table(pcoa_wuf_df,
    file = "results/export/beta/weighted_unifrac_pcoa_coords.tsv",
    sep = "\t", row.names = FALSE, quote = FALSE)
  cat("       [OK] results/export/beta/weighted_unifrac_pcoa_coords.tsv\n")

  # Save variance explained
  var_exp_wuf_df <- data.frame(
    Axis = paste0("PCo", seq_along(var_exp_wuf)),
    Variance_percent = var_exp_wuf,
    Cumulative_percent = cumsum(var_exp_wuf)
  )
  write.table(var_exp_wuf_df,
    file = "results/export/beta/weighted_unifrac_pcoa_variance.tsv",
    sep = "\t", row.names = FALSE, quote = FALSE)
  cat("       [OK] results/export/beta/weighted_unifrac_pcoa_variance.tsv\n")

  # Save full PERMANOVA results
  adonis_wuf_out <- as.data.frame(adonis_wuf)
  adonis_wuf_out$Term <- rownames(adonis_wuf)
  adonis_wuf_out <- adonis_wuf_out[, c("Term", setdiff(colnames(adonis_wuf_out), "Term"))]
  write.table(adonis_wuf_out,
    file = "results/export/beta/weighted_unifrac_permanova.tsv",
    sep = "\t", row.names = FALSE, quote = FALSE)
  cat("       [OK] results/export/beta/weighted_unifrac_permanova.tsv\n")
} else {
  cat("       [Skipped] Weighted UniFrac distance matrix not found (weighted_unifrac_distance_matrix.tsv)\n")
  cat("       Please ensure qiime diversity core-metrics-phylogenetic has been run and exported\n")
}

# ---------- 8d. Unweighted UniFrac PCoA ----------
cat("       Unweighted UniFrac PCoA...\n")
uuf_dist_file <- "results/export/unweighted_unifrac_distance_matrix.tsv"
if (file.exists(uuf_dist_file)) {
  uuf_dist <- as.matrix(read.table(uuf_dist_file, sep = "\t", header = TRUE, row.names = 1, check.names = FALSE))

  pcoa_uuf <- cmdscale(uuf_dist, k = min(10, nrow(uuf_dist) - 1), eig = TRUE)
  var_exp_uuf <- round(pcoa_uuf$eig[1:4] / sum(pcoa_uuf$eig[pcoa_uuf$eig > 0]) * 100, 1)

  pcoa_uuf_df <- as.data.frame(pcoa_uuf$points)
  colnames(pcoa_uuf_df) <- paste0("PCo", seq_len(ncol(pcoa_uuf_df)))
  pcoa_uuf_df$SampleID <- rownames(pcoa_uuf_df)
  pcoa_uuf_df <- merge(pcoa_uuf_df, metadata[, group_col, drop = FALSE],
                        by.x = "SampleID", by.y = "row.names")

  # PERMANOVA
  adonis_uuf <- adonis2(as.formula(paste("uuf_dist ~", group_col)),
                         data = metadata, permutations = 999)
  print(adonis_uuf)
  r2_uuf <- round(adonis_uuf[1, "R2"], 3)
  p_col_uuf <- grep("Pr", colnames(adonis_uuf))[1]
  pval_uuf <- adonis_uuf[1, p_col_uuf]
  pval_uuf_str <- ifelse(pval_uuf < 0.001, format.pval(pval_uuf, digits = 4),
                          paste0("= ", format.pval(pval_uuf, digits = 4)))

  # PCoA plot
  p_uuf <- ggplot(pcoa_uuf_df, aes(x = PCo1, y = PCo2, color = !!sym(group_col))) +
    geom_point(size = 3, alpha = 0.8)

  if (min_group_size >= 4) {
    p_uuf <- p_uuf +
      stat_ellipse(aes(fill = !!sym(group_col)),
        geom = "polygon", alpha = 0.1, level = 0.95, show.legend = FALSE)
  }

  p_uuf <- p_uuf +
    scale_color_manual(values = get_group_colors(nlevels(pcoa_uuf_df[[group_col]]))) +
    scale_fill_manual(values = get_group_colors(nlevels(pcoa_uuf_df[[group_col]]))) +
    labs(title = "Beta Diversity - Unweighted UniFrac PCoA",
         x = paste0("PCo1 (", var_exp_uuf[1], "%)"),
         y = paste0("PCo2 (", var_exp_uuf[2], "%)"),
         color = group_col,
         caption = paste0("PERMANOVA: R² = ", r2_uuf, ", p ", pval_uuf_str)) +
    theme_bw(base_size = 14) +
    theme(plot.title = element_text(hjust = 0.5, face = "bold"),
          legend.position = "right", panel.grid.minor = element_blank(),
          plot.caption = element_text(hjust = 0.5, size = 10))

  ggsave(filename = "results/export/beta/beta_diversity_pcoa_unweighted_unifrac.pdf",
         plot = p_uuf, width = 8, height = 6, device = cairo_pdf)
  cat("       [OK] results/export/beta/beta_diversity_pcoa_unweighted_unifrac.pdf\n")

  # Save PCoA coordinates
  write.table(pcoa_uuf_df,
    file = "results/export/beta/unweighted_unifrac_pcoa_coords.tsv",
    sep = "\t", row.names = FALSE, quote = FALSE)
  cat("       [OK] results/export/beta/unweighted_unifrac_pcoa_coords.tsv\n")

  # Save variance explained
  var_exp_uuf_df <- data.frame(
    Axis = paste0("PCo", seq_along(var_exp_uuf)),
    Variance_percent = var_exp_uuf,
    Cumulative_percent = cumsum(var_exp_uuf)
  )
  write.table(var_exp_uuf_df,
    file = "results/export/beta/unweighted_unifrac_pcoa_variance.tsv",
    sep = "\t", row.names = FALSE, quote = FALSE)
  cat("       [OK] results/export/beta/unweighted_unifrac_pcoa_variance.tsv\n")

  # Save full PERMANOVA results
  adonis_uuf_out <- as.data.frame(adonis_uuf)
  adonis_uuf_out$Term <- rownames(adonis_uuf)
  adonis_uuf_out <- adonis_uuf_out[, c("Term", setdiff(colnames(adonis_uuf_out), "Term"))]
  write.table(adonis_uuf_out,
    file = "results/export/beta/unweighted_unifrac_permanova.tsv",
    sep = "\t", row.names = FALSE, quote = FALSE)
  cat("       [OK] results/export/beta/unweighted_unifrac_permanova.tsv\n")
} else {
  cat("       [Skipped] Unweighted UniFrac distance matrix not found (unweighted_unifrac_distance_matrix.tsv)\n")
  cat("       Please ensure qiime diversity core-metrics-phylogenetic has been run and exported\n")
}

cat("\n")

# ============================================================
# 9. Phylum-level stacked barplot
# ============================================================

cat("       Processing phylum-level composition...\n")

# Map each ASV to its phylum
asv_phylum <- setNames(taxonomy$Phylum, taxonomy$FeatureID)

# Keep only ASVs present in the feature table
common_asvs <- intersect(names(asv_phylum), rownames(feature_table))
asv_phylum <- asv_phylum[common_asvs]
ft_phylum <- feature_table[common_asvs, , drop = FALSE]

if (length(common_asvs) > 0) {
  # Aggregate counts by phylum
  phylum_levels <- unique(asv_phylum)
  phylum_counts <- matrix(0, nrow = length(phylum_levels), ncol = ncol(ft_phylum))
  rownames(phylum_counts) <- phylum_levels
  colnames(phylum_counts) <- colnames(ft_phylum)

  for (i in seq_along(asv_phylum)) {
    phylum_counts[asv_phylum[i], ] <- phylum_counts[asv_phylum[i], ] + ft_phylum[i, ]
  }

  # Convert to relative abundance (%)
  phylum_rel <- sweep(phylum_counts, 2, colSums(phylum_counts), "/") * 100

  # Reshape to long format
  phylum_df <- as.data.frame(phylum_rel)
  phylum_df$Phylum <- rownames(phylum_df)

  phylum_long <- pivot_longer(phylum_df, cols = -Phylum, names_to = "SampleID", values_to = "Abundance")
  phylum_long <- merge(phylum_long, metadata[, group_col, drop = FALSE],
                       by.x = "SampleID", by.y = "row.names")

  # Merge low-abundance phyla into Others
  phylum_mean_abund <- aggregate(Abundance ~ Phylum, data = phylum_long, FUN = mean)
  phylum_mean_abund <- phylum_mean_abund[order(phylum_mean_abund$Abundance, decreasing = TRUE), ]
  top_phyla_stacked <- head(phylum_mean_abund$Phylum, top_n_phyla_stacked)
  phylum_long$Phylum_display <- ifelse(
    phylum_long$Phylum %in% top_phyla_stacked,
    phylum_long$Phylum,
    "Others"
  )
  phylum_long$Phylum_display <- factor(phylum_long$Phylum_display,
    levels = c(top_phyla_stacked, "Others"))

  # Color: Top phyla from ggsci palette, Others in grey
  n_top <- length(top_phyla_stacked)
  stk_colors <- get_group_colors(max(n_top, 3))[1:n_top]
  stk_colors <- setNames(c(stk_colors, "#BBBBBB"), c(top_phyla_stacked, "Others"))

  # Sort samples by group
  sample_levels <- unique(as.character(phylum_long$SampleID))
  sample_levels <- sample_levels[order(phylum_long[[group_col]][match(sample_levels, phylum_long$SampleID)])]
  phylum_long$SampleID <- factor(phylum_long$SampleID, levels = sample_levels)

  p_phylum_bar <- ggplot(phylum_long, aes(x = SampleID, y = Abundance, fill = Phylum_display)) +
    geom_bar(stat = "identity", width = min(0.95, 18 / ncol(feature_table))) +
    scale_fill_manual(values = stk_colors) +
    labs(
      title = "Phylum Composition (Relative Abundance)",
      x = "Sample",
      y = "Relative Abundance (%)",
      fill = "Phylum"
    ) +
    theme_bw(base_size = 12) +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),
      axis.text.x = element_text(angle = 60, hjust = 1, size = 8),
      legend.position = "bottom",
      legend.text = element_text(size = 7),
      legend.key.size = unit(0.4, "cm"),
      panel.grid.major.x = element_blank()
    ) +
    guides(fill = guide_legend(ncol = 4)) +
    facet_grid(as.formula(paste("~", group_col)), scales = "free_x", space = "free")

  ggsave(
    filename = "results/export/taxa/phylum_stacked_barplot.pdf",
    plot = p_phylum_bar,
    width = max(8, min(ncol(feature_table) * 0.35, 25)),
    height = 6,
    device = cairo_pdf
  )
  cat("       [OK] results/export/taxa/phylum_stacked_barplot.pdf\n")

  # Save phylum-level relative abundance table
  phylum_rel_df <- as.data.frame(phylum_rel)
  phylum_rel_df$Phylum <- rownames(phylum_rel_df)
  phylum_rel_df <- phylum_rel_df[, c("Phylum", setdiff(colnames(phylum_rel_df), "Phylum"))]
  write.table(phylum_rel_df,
    file = "results/export/feature_tables/phylum_relative_abundance.tsv",
    sep = "\t", row.names = FALSE, quote = FALSE)
  cat("       [OK] results/export/feature_tables/phylum_relative_abundance.tsv\n")

  # ============================================================
  # 10. Phylum-level abundance barplot (aggregated)
  # ============================================================

  # Calculate per-group mean relative abundance
  phylum_group_mean <- phylum_long %>%
    group_by(!!sym(group_col), Phylum) %>%
    summarise(MeanAbundance = mean(Abundance), SD = sd(Abundance), .groups = "drop")

  # Calculate overall mean
  phylum_overall <- phylum_long %>%
    group_by(Phylum) %>%
    summarise(MeanAbundance = mean(Abundance), SD = sd(Abundance), .groups = "drop") %>%
    arrange(desc(MeanAbundance))
  phylum_overall[[group_col]] <- "Overall"

  # Top N phyla, merge rest as Others
  top_n_phyla <- 7
  top_phyla <- phylum_overall$Phylum[1:min(top_n_phyla, nrow(phylum_overall))]
  top_phyla <- top_phyla[top_phyla != "Unassigned"]
  top_phyla <- c(top_phyla, "Unassigned")

  phylum_group_mean$Phylum_grouped <- ifelse(
    phylum_group_mean$Phylum %in% top_phyla,
    phylum_group_mean$Phylum,
    "Others"
  )

  phylum_grouped <- phylum_group_mean %>%
    group_by(!!sym(group_col), Phylum_grouped) %>%
    summarise(MeanAbundance = sum(MeanAbundance), .groups = "drop")

  # Order by overall relative abundance descending; Others always at bottom
  phylum_grouped$Phylum_grouped <- factor(phylum_grouped$Phylum_grouped,
    levels = c(top_phyla, "Others"))

  phyla_group_levels <- levels(phylum_grouped$Phylum_grouped)
  phyla_group_levels <- phyla_group_levels[phyla_group_levels != "Others"]
  phy_colors <- pal_jco()(10)
  phy_colors <- grDevices::colorRampPalette(phy_colors)(length(phyla_group_levels))
  names(phy_colors) <- phyla_group_levels
  all_colors <- c(phy_colors, c("Others" = "#A9A9A9"))

  p_phylum_abundance <- ggplot(phylum_grouped,
                               aes(x = !!sym(group_col), y = MeanAbundance,
                                   fill = Phylum_grouped)) +
    geom_bar(stat = "identity", width = 0.7) +
    scale_fill_manual(values = all_colors) +
    labs(
      title = paste0("Top ", top_n_phyla, " Phyla (Mean Relative Abundance)"),
      x = group_col,
      y = "Mean Relative Abundance (%)",
      fill = "Phylum"
    ) +
    theme_bw(base_size = 14) +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),
      axis.text.x = element_text(angle = 45, hjust = 1),
      legend.position = "right"
    )

  ggsave(
    filename = "results/export/taxa/phylum_abundance_barchart.pdf",
    plot = p_phylum_abundance,
    width = 7,
    height = 6,
    device = cairo_pdf
  )
  cat("       [OK] results/export/taxa/phylum_abundance_barchart.pdf\n")

  # ============================================================
  # 11. Genus-level heatmap
  # ============================================================

  cat("       Generating genus-level heatmap...\n")

  # Map ASVs to genus
  asv_genus <- setNames(taxonomy$Genus, taxonomy$FeatureID)
  asv_genus <- asv_genus[common_asvs]

  # Aggregate by genus
  genus_levels <- unique(asv_genus)
  genus_counts <- matrix(0, nrow = length(genus_levels), ncol = ncol(ft_phylum))
  rownames(genus_counts) <- genus_levels
  colnames(genus_counts) <- colnames(ft_phylum)

  for (i in seq_along(asv_genus)) {
    genus_counts[asv_genus[i], ] <- genus_counts[asv_genus[i], ] + ft_phylum[i, ]
  }

  # Remove Unassigned
  if ("Unassigned" %in% rownames(genus_counts)) {
    genus_counts <- genus_counts[rownames(genus_counts) != "Unassigned", , drop = FALSE]
  }

  # Select Top N genera
  genus_total_abundance <- rowSums(genus_counts)
  genus_sorted <- sort(genus_total_abundance, decreasing = TRUE)
  top_genera <- names(genus_sorted)[1:min(top_n_genera, length(genus_sorted))]

  if (length(top_genera) >= 3) {
    genus_heatmap_data <- genus_counts[top_genera, , drop = FALSE]

    # Log10 transform (add pseudocount to avoid log(0))
    genus_heatmap_log <- log10(genus_heatmap_data + 1)

    # Sample group annotation
    sample_groups <- metadata[colnames(genus_heatmap_log), group_col, drop = FALSE]
    annotation_colors <- list()
    annotation_colors[[group_col]] <- setNames(
      get_group_colors(nlevels(sample_groups[[group_col]])),
      levels(sample_groups[[group_col]])
    )

    cairo_pdf("results/export/heatmap/genus_heatmap.pdf",
        width = max(8, ncol(genus_heatmap_log) * 0.4),
        height = max(6, nrow(genus_heatmap_log) * 0.35))
    pheatmap(
      genus_heatmap_log,
      annotation_col = sample_groups,
      annotation_colors = annotation_colors,
      cluster_rows = TRUE,
      cluster_cols = TRUE,
      show_rownames = TRUE,
      show_colnames = TRUE,
      fontsize_row = 8,
      fontsize_col = 7,
      color = colorRampPalette(c("#4DBBD5", "white", "#E64B35"))(100),
      main = paste0("Top ", length(top_genera), " Genera (log10 Abundance)"),
      border_color = NA
    )
    dev.off()
    cat("       [OK] results/export/heatmap/genus_heatmap.pdf\n")
  } else {
    cat("       [Skipped] Too few annotated genera for heatmap (< 3)\n")
  }

  # ============================================================
  # 12. Save genus-level abundance table
  # ============================================================

  genus_abundance_df <- as.data.frame(genus_counts)
  genus_abundance_df$Genus <- rownames(genus_abundance_df)
  genus_abundance_df <- genus_abundance_df[, c("Genus", setdiff(colnames(genus_abundance_df), "Genus"))]

  write.table(
    genus_abundance_df,
    file = "results/export/feature_tables/genus_abundance.tsv",
    sep = "\t",
    row.names = FALSE,
    quote = FALSE
  )
  cat("       [OK] results/export/feature_tables/genus_abundance.tsv\n")
} else {
  cat("       [Skipped] No common ASVs between feature table and taxonomy\n")
}

# ============================================================
# 13. FAPROTAX input files
# ============================================================

cat("\n[6/8] Preparing FAPROTAX input files...\n")

# FAPROTAX requires a rarefied feature table (BIOM format) and taxonomy file
# Copy rarefied_table.biom and taxonomy.tsv to results/export/faprotax/

if (file.exists(rarefied_biom_file)) {
  file.copy(rarefied_biom_file, "results/export/faprotax/rarefied_table.biom", overwrite = TRUE)
  cat("       [OK] results/export/faprotax/rarefied_table.biom\n")
} else {
  cat("       [Skipped] Rarefied table not found (", rarefied_biom_file, ")\n")
}

if (file.exists(taxonomy_file)) {
  tax_raw <- read.table(taxonomy_file, sep = "\t", header = TRUE,
    check.names = FALSE, stringsAsFactors = FALSE)
  tax_faprotax <- tax_raw[, c("Feature ID", "Taxon")]
  # Write in binary mode to avoid Windows CRLF line endings
  con <- file("results/export/faprotax/taxonomy.tsv", "wb")
  write.table(tax_faprotax, file = con,
    sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
  close(con)
  cat("       [OK] results/export/faprotax/taxonomy.tsv (header and Confidence column removed)\n")
} else {
  cat("       [Skipped] Taxonomy file not found (", taxonomy_file, ")\n")
}

# ============================================================
# 14. PICRUSt2 input file preparation
# ============================================================

cat("\n[7/8] Preparing PICRUSt2 input files...\n")

# Copy processed feature-table.tsv (PICRUSt2 input)
# Remove the first line "# Constructed from biom file" and change "#OTU ID" to "#OTUID"
if (file.exists(feature_table_file)) {
  ft_lines <- readLines(feature_table_file)
  ft_lines <- ft_lines[-1]
  ft_lines[1] <- sub("#OTU ID", "#OTUID", ft_lines[1])
  # Write in binary mode to avoid Windows CRLF line endings
  con <- file("results/export/picrust2/feature-table.tsv", "wb")
  writeLines(ft_lines, con)
  close(con)
  cat("       [OK] results/export/picrust2/feature-table.tsv\n")
} else {
  cat("       [Skipped] Feature table not found\n")
}

# Copy representative sequences
if (file.exists(dna_sequences_file)) {
  file.copy(dna_sequences_file, "results/export/picrust2/dna-sequences.fasta", overwrite = TRUE)
  cat("       [OK] results/export/picrust2/dna-sequences.fasta\n")
} else {
  cat("       [Skipped] dna-sequences.fasta not found\n")
}


# ============================================================
# 15. Completion summary
# ============================================================

cat("\n[8/8] Pipeline complete!\n")
cat("========================================\n")
cat("Output file summary:\n")
cat("========================================\n")
cat("  results/export/alpha/alpha_diversity_boxplot.pdf              -- Alpha diversity boxplots (5 metrics with significance stars, K-W p-values)\n")
cat("  results/export/alpha/rarefaction_curves.pdf                  -- Rarefaction curves\n")
cat("  results/export/beta/beta_diversity_pcoa_bray_curtis.pdf      -- Beta diversity Bray-Curtis PCoA (PERMANOVA annotation)\n")
cat("  results/export/beta/beta_diversity_pcoa_jaccard.pdf          -- Beta diversity Jaccard PCoA (PERMANOVA annotation)\n")
cat("  results/export/beta/beta_diversity_pcoa_weighted_unifrac.pdf      -- Beta diversity Weighted UniFrac PCoA (PERMANOVA annotation)\n")
cat("  results/export/beta/beta_diversity_pcoa_unweighted_unifrac.pdf    -- Beta diversity Unweighted UniFrac PCoA (PERMANOVA annotation)\n")
cat("  results/export/beta/bray_curtis_pcoa_coords.tsv                -- Bray-Curtis PCoA coordinates\n")
cat("  results/export/beta/bray_curtis_pcoa_variance.tsv              -- Bray-Curtis PCoA variance explained\n")
cat("  results/export/beta/bray_curtis_permanova.tsv                  -- Bray-Curtis PERMANOVA results\n")
cat("  results/export/beta/jaccard_pcoa_coords.tsv                    -- Jaccard PCoA coordinates\n")
cat("  results/export/beta/jaccard_pcoa_variance.tsv                  -- Jaccard PCoA variance explained\n")
cat("  results/export/beta/jaccard_permanova.tsv                      -- Jaccard PERMANOVA results\n")
cat("  results/export/beta/weighted_unifrac_pcoa_coords.tsv           -- Weighted UniFrac PCoA coordinates\n")
cat("  results/export/beta/weighted_unifrac_pcoa_variance.tsv         -- Weighted UniFrac PCoA variance explained\n")
cat("  results/export/beta/weighted_unifrac_permanova.tsv             -- Weighted UniFrac PERMANOVA results\n")
cat("  results/export/beta/unweighted_unifrac_pcoa_coords.tsv         -- Unweighted UniFrac PCoA coordinates\n")
cat("  results/export/beta/unweighted_unifrac_pcoa_variance.tsv       -- Unweighted UniFrac PCoA variance explained\n")
cat("  results/export/beta/unweighted_unifrac_permanova.tsv           -- Unweighted UniFrac PERMANOVA results\n")
cat("  results/export/taxa/phylum_stacked_barplot.pdf                 -- Phylum-level stacked barplot\n")
cat("  results/export/taxa/phylum_abundance_barchart.pdf              -- Phylum-level abundance barplot\n")
cat("  results/export/heatmap/genus_heatmap.pdf                       -- Genus-level heatmap\n")
cat("  results/export/faprotax/rarefied_table.biom                    -- FAPROTAX input (rarefied feature table)\n")
cat("  results/export/faprotax/taxonomy.tsv                           -- FAPROTAX input (taxonomy)\n")
cat("  results/export/picrust2/feature-table.tsv                      -- PICRUSt2 feature table\n")
cat("  results/export/picrust2/dna-sequences.fasta                    -- PICRUSt2 representative sequences\n")
cat("  results/export/feature_tables/taxonomy_processed.tsv           -- Taxonomy parsed by level\n")
cat("  results/export/feature_tables/genus_abundance.tsv              -- Genus-level abundance table\n")
cat("  results/export/feature_tables/alpha_diversity_metrics.tsv      -- Alpha diversity metrics\n")
cat("  results/export/feature_tables/feature_table_with_taxonomy.tsv  -- Feature table with taxonomy\n")
cat("========================================\n")
cat("Script ran successfully!\n")
